server:
  port: 1030
spring:
  application:
    name: zuul-gateway
zuul:
  routes:
    sysmanage.serviceId: hrm-sysmanage
    sysmanage.path: /sysmanage/**
    common.serviceId: hrm-common
    common.path: /common/**
    course.serviceId: hrm-course
    course.path: /course/**
  ignored-services: "*"
  prefix: "/services"
retryable: true
ribbon:
  ConnectTimeout: 250
  ReadTimeout: 2000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 3000