server:
  port: 2050
spring:
  application:
    name: hrm-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm-user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:com/erocraft/mapper/*Mapper.xml
  type-aliases-package: com.erocraft.domain,com.erocraft.query