server:
  port: 2020
spring:
  application:
    name: hrm-course
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm-course?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
mybatis-plus:
  mapper-locations: classpath:com/erocraft/mapper/*Mapper.xml
  type-aliases-package: com.erocraft.domain,cn.itsource.query